{{- if .Values.storage.enabled }}
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: {{ include "rstudio.fullname" . }}
  labels:
    {{- include "rstudio.labels" . | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
